<?php

namespace Modules\Reporting\Filament\Pages;

use Modules\Auth\Models\User;
use Modules\Booking\Models\Appointment;
use Modules\Billing\Models\Payment;
use Modules\Staff\Models\StaffCommissionRecord;
use Illuminate\Support\Facades\DB;

class StaffPerformanceReportPage extends BaseReportPage
{
    protected static ?string $navigationIcon = 'heroicon-o-user-group';

    protected static ?int $navigationSort = 5;

    public static function getNavigationParentItem(): ?string
    {
        return __('core::core.nav_folders.rpt_staff');
    }


    public static function getNavigationLabel(): string
    {
        return __('reporting::reporting.staff_performance_report');
    }

    public function getTitle(): string
    {
        return __('reporting::reporting.staff_performance_report');
    }

    protected function getReportTitle(): string
    {
        return __('reporting::reporting.staff_performance_report');
    }

    protected function loadReportData(): void
    {
        $startDate = $this->getStartDate();
        $endDate = $this->getEndDate();
        $branchId = $this->getBranchId();

        // Total practitioners
        $practitionersQuery = User::query()
            ->whereHas('roles', fn ($q) => $q->whereIn('name', ['practitioner', 'doctor', 'therapist']));

        if ($branchId) {
            $practitionersQuery->where('branch_id', $branchId);
        }

        $totalPractitioners = $practitionersQuery->count();

        // Completed appointments by practitioners
        $appointmentsQuery = Appointment::query()
            ->whereBetween('date', [$startDate, $endDate])
            ->where('status', 'completed');

        if ($branchId) {
            $appointmentsQuery->where('branch_id', $branchId);
        }

        $totalCompletedAppointments = $appointmentsQuery->count();

        // Revenue generated by staff
        $revenueQuery = DB::table('payments')
            ->join('invoices', 'payments.invoice_id', '=', 'invoices.id')
            ->join('appointments', 'invoices.appointment_id', '=', 'appointments.id')
            ->whereBetween('payments.paid_at', [$startDate, $endDate]);

        if ($branchId) {
            $revenueQuery->where('invoices.branch_id', $branchId);
        }

        $totalRevenue = $revenueQuery->sum('payments.amount_minor');

        // Total commissions paid
        $commissionsQuery = StaffCommissionRecord::query()
            ->whereBetween('created_at', [$startDate, $endDate]);

        $totalCommissions = $commissionsQuery->sum('amount_minor');
        $pendingCommissions = (clone $commissionsQuery)->where('status', 'pending')->sum('amount_minor');

        // Stats cards
        $this->stats = [
            [
                'label' => __('reporting::reporting.total_practitioners'),
                'value' => number_format($totalPractitioners),
                'icon' => 'heroicon-o-user-group',
                'color' => 'primary',
            ],
            [
                'label' => __('reporting::reporting.appointments_completed'),
                'value' => number_format($totalCompletedAppointments),
                'description' => $totalPractitioners > 0
                    ? round($totalCompletedAppointments / $totalPractitioners) . ' ' . __('reporting::reporting.per_practitioner')
                    : '',
                'icon' => 'heroicon-o-calendar-days',
                'color' => 'success',
            ],
            [
                'label' => __('reporting::reporting.revenue_generated'),
                'value' => $this->formatCurrency($totalRevenue),
                'icon' => 'heroicon-o-banknotes',
                'color' => 'info',
            ],
            [
                'label' => __('reporting::reporting.commissions'),
                'value' => $this->formatCurrency($totalCommissions),
                'description' => $this->formatCurrency($pendingCommissions) . ' ' . __('reporting::reporting.pending'),
                'icon' => 'heroicon-o-currency-dollar',
                'color' => 'warning',
            ],
        ];

        // Performance by practitioner
        $performanceByPractitioner = DB::table('appointments')
            ->join('users', 'appointments.practitioner_id', '=', 'users.id')
            ->leftJoin('invoices', 'invoices.appointment_id', '=', 'appointments.id')
            ->leftJoin('payments', 'payments.invoice_id', '=', 'invoices.id')
            ->whereBetween('appointments.date', [$startDate, $endDate])
            ->where('appointments.status', 'completed')
            ->when($branchId, fn ($q) => $q->where('appointments.branch_id', $branchId))
            ->groupBy('users.id', 'users.first_name', 'users.last_name')
            ->select(
                'users.id',
                DB::raw("CONCAT(users.first_name, ' ', users.last_name) as name"),
                DB::raw('COUNT(DISTINCT appointments.id) as appointments'),
                DB::raw('COALESCE(SUM(payments.amount_minor), 0) as revenue')
            )
            ->orderByDesc('revenue')
            ->limit(10)
            ->get();

        // Appointments by practitioner for chart
        $this->chartData = [
            'labels' => $performanceByPractitioner->pluck('name')->toArray(),
            'datasets' => [
                [
                    'label' => __('reporting::reporting.appointments'),
                    'data' => $performanceByPractitioner->pluck('appointments')->toArray(),
                    'backgroundColor' => 'rgba(59, 130, 246, 0.7)',
                    'yAxisID' => 'y',
                ],
                [
                    'label' => __('reporting::reporting.revenue') . ' (EGP)',
                    'data' => $performanceByPractitioner->pluck('revenue')->map(fn ($v) => $v / 100)->toArray(),
                    'backgroundColor' => 'rgba(34, 197, 94, 0.7)',
                    'yAxisID' => 'y1',
                ],
            ],
        ];

        // Table data
        $this->tableData = $performanceByPractitioner->map(fn ($item) => [
            'practitioner' => $item->name,
            'appointments' => $item->appointments,
            'revenue' => $this->formatCurrency($item->revenue),
            'avg_revenue' => $item->appointments > 0
                ? $this->formatCurrency($item->revenue / $item->appointments)
                : '0 EGP',
        ])->toArray();
    }

    protected function getStatsCards(): array
    {
        return $this->stats;
    }

    protected function getChartConfig(): array
    {
        return [
            'type' => 'bar',
            'data' => $this->chartData,
            'options' => [
                'responsive' => true,
                'plugins' => [
                    'title' => [
                        'display' => true,
                        'text' => __('reporting::reporting.performance_by_practitioner'),
                    ],
                ],
                'scales' => [
                    'y' => [
                        'type' => 'linear',
                        'display' => true,
                        'position' => 'left',
                        'title' => ['display' => true, 'text' => __('reporting::reporting.appointments')],
                    ],
                    'y1' => [
                        'type' => 'linear',
                        'display' => true,
                        'position' => 'right',
                        'title' => ['display' => true, 'text' => __('reporting::reporting.revenue')],
                        'grid' => ['drawOnChartArea' => false],
                    ],
                ],
            ],
        ];
    }

    protected function getTableColumns(): array
    {
        return [
            ['key' => 'practitioner', 'label' => __('reporting::reporting.practitioner')],
            ['key' => 'appointments', 'label' => __('reporting::reporting.appointments')],
            ['key' => 'revenue', 'label' => __('reporting::reporting.revenue')],
            ['key' => 'avg_revenue', 'label' => __('reporting::reporting.avg_revenue_per_appointment')],
        ];
    }
}
