<?php

namespace Modules\Equipment\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Equipment\Models\EquipmentParameterTemplate;

class EquipmentParameterTemplatesSeeder extends Seeder
{
    public function run(): void
    {
        $templates = [
            $this->getLaserEquipmentTemplate(),
            $this->getIPLEquipmentTemplate(),
            $this->getRFEquipmentTemplate(),
            $this->getHIFUEquipmentTemplate(),
            $this->getCryolipolysisEquipmentTemplate(),
            $this->getMicroneedlingEquipmentTemplate(),
            $this->getHydrafacialEquipmentTemplate(),
            $this->getLEDEquipmentTemplate(),
        ];

        foreach ($templates as $template) {
            EquipmentParameterTemplate::updateOrCreate(
                ['template_code' => $template['template_code']],
                $template
            );
        }
    }

    protected function getLaserEquipmentTemplate(): array
    {
        return [
            'tenant_id' => null,
            'template_name' => 'Laser Equipment',
            'template_code' => 'EQUIP_LASER',
            'description' => 'Standard tracking parameters for laser devices (Diode, Alexandrite, Nd:YAG)',
            'equipment_category' => 'laser',
            'is_system' => true,
            'is_active' => true,
            'parameters' => [
                [
                    'key' => 'wavelength',
                    'type' => 'select',
                    'label' => ['en' => 'Wavelength', 'ar' => 'الطول الموجي'],
                    'required' => true,
                    'unit' => 'nm',
                    'category' => 'energy',
                    'options' => [
                        ['value' => '755', 'label' => ['en' => '755nm (Alexandrite)', 'ar' => '755nm (الكسندريت)']],
                        ['value' => '808', 'label' => ['en' => '808nm (Diode)', 'ar' => '808nm (ديود)']],
                        ['value' => '810', 'label' => ['en' => '810nm (Diode)', 'ar' => '810nm (ديود)']],
                        ['value' => '940', 'label' => ['en' => '940nm (Diode)', 'ar' => '940nm (ديود)']],
                        ['value' => '1064', 'label' => ['en' => '1064nm (Nd:YAG)', 'ar' => '1064nm (ند:ياج)']],
                    ],
                ],
                [
                    'key' => 'fluence',
                    'type' => 'decimal',
                    'label' => ['en' => 'Fluence', 'ar' => 'كثافة الطاقة'],
                    'required' => true,
                    'unit' => 'J/cm²',
                    'category' => 'energy',
                    'min' => 1,
                    'max' => 100,
                    'step' => 0.5,
                    'default_value' => 20,
                    'cumulative' => false,
                ],
                [
                    'key' => 'pulse_duration',
                    'type' => 'number',
                    'label' => ['en' => 'Pulse Duration', 'ar' => 'مدة النبضة'],
                    'required' => true,
                    'unit' => 'ms',
                    'category' => 'timing',
                    'min' => 1,
                    'max' => 1000,
                    'step' => 1,
                    'default_value' => 30,
                ],
                [
                    'key' => 'spot_size',
                    'type' => 'select',
                    'label' => ['en' => 'Spot Size', 'ar' => 'حجم البقعة'],
                    'required' => true,
                    'unit' => 'mm',
                    'category' => 'delivery',
                    'options' => [
                        ['value' => '6', 'label' => ['en' => '6mm', 'ar' => '6مم']],
                        ['value' => '8', 'label' => ['en' => '8mm', 'ar' => '8مم']],
                        ['value' => '10', 'label' => ['en' => '10mm', 'ar' => '10مم']],
                        ['value' => '12', 'label' => ['en' => '12mm', 'ar' => '12مم']],
                        ['value' => '15', 'label' => ['en' => '15mm', 'ar' => '15مم']],
                        ['value' => '18', 'label' => ['en' => '18mm', 'ar' => '18مم']],
                        ['value' => '20', 'label' => ['en' => '20mm', 'ar' => '20مم']],
                        ['value' => '24', 'label' => ['en' => '24mm', 'ar' => '24مم']],
                    ],
                    'default_value' => '12',
                ],
                [
                    'key' => 'repetition_rate',
                    'type' => 'number',
                    'label' => ['en' => 'Repetition Rate', 'ar' => 'معدل التكرار'],
                    'required' => false,
                    'unit' => 'Hz',
                    'category' => 'timing',
                    'min' => 1,
                    'max' => 20,
                    'default_value' => 3,
                ],
                [
                    'key' => 'cooling_level',
                    'type' => 'select',
                    'label' => ['en' => 'Cooling Level', 'ar' => 'مستوى التبريد'],
                    'required' => true,
                    'category' => 'cooling',
                    'options' => [
                        ['value' => 'off', 'label' => ['en' => 'Off', 'ar' => 'إيقاف']],
                        ['value' => 'low', 'label' => ['en' => 'Low', 'ar' => 'منخفض']],
                        ['value' => 'medium', 'label' => ['en' => 'Medium', 'ar' => 'متوسط']],
                        ['value' => 'high', 'label' => ['en' => 'High', 'ar' => 'عالي']],
                        ['value' => 'max', 'label' => ['en' => 'Maximum', 'ar' => 'أقصى']],
                    ],
                    'default_value' => 'high',
                ],
                [
                    'key' => 'cooling_temp',
                    'type' => 'number',
                    'label' => ['en' => 'Cooling Temperature', 'ar' => 'درجة التبريد'],
                    'required' => false,
                    'unit' => '°C',
                    'category' => 'cooling',
                    'min' => -10,
                    'max' => 25,
                    'default_value' => 5,
                ],
                [
                    'key' => 'shots_fired',
                    'type' => 'number',
                    'label' => ['en' => 'Shots Fired', 'ar' => 'عدد النبضات'],
                    'required' => false,
                    'unit' => 'shots',
                    'category' => 'other',
                    'min' => 0,
                    'max' => 50000,
                    'cumulative' => true,
                    'help_text' => ['en' => 'Number of shots/pulses fired during this session', 'ar' => 'عدد النبضات خلال هذه الجلسة'],
                ],
            ],
        ];
    }

    protected function getIPLEquipmentTemplate(): array
    {
        return [
            'tenant_id' => null,
            'template_name' => 'IPL Equipment',
            'template_code' => 'EQUIP_IPL',
            'description' => 'Standard tracking parameters for Intense Pulsed Light devices',
            'equipment_category' => 'ipl',
            'is_system' => true,
            'is_active' => true,
            'parameters' => [
                [
                    'key' => 'wavelength_filter',
                    'type' => 'select',
                    'label' => ['en' => 'Wavelength Filter', 'ar' => 'مرشح الطول الموجي'],
                    'required' => true,
                    'unit' => 'nm',
                    'category' => 'energy',
                    'options' => [
                        ['value' => '420', 'label' => ['en' => '420nm (Acne)', 'ar' => '420nm (حب الشباب)']],
                        ['value' => '515', 'label' => ['en' => '515nm (Pigment)', 'ar' => '515nm (تصبغ)']],
                        ['value' => '560', 'label' => ['en' => '560nm (Skin Rejuvenation)', 'ar' => '560nm (تجديد البشرة)']],
                        ['value' => '590', 'label' => ['en' => '590nm (Vascular)', 'ar' => '590nm (أوعية دموية)']],
                        ['value' => '640', 'label' => ['en' => '640nm (Hair Removal)', 'ar' => '640nm (إزالة الشعر)']],
                        ['value' => '690', 'label' => ['en' => '690nm (Deep Hair)', 'ar' => '690nm (شعر عميق)']],
                    ],
                ],
                [
                    'key' => 'fluence',
                    'type' => 'decimal',
                    'label' => ['en' => 'Fluence', 'ar' => 'كثافة الطاقة'],
                    'required' => true,
                    'unit' => 'J/cm²',
                    'category' => 'energy',
                    'min' => 5,
                    'max' => 50,
                    'step' => 0.5,
                    'default_value' => 15,
                ],
                [
                    'key' => 'pulse_duration',
                    'type' => 'number',
                    'label' => ['en' => 'Pulse Duration', 'ar' => 'مدة النبضة'],
                    'required' => true,
                    'unit' => 'ms',
                    'category' => 'timing',
                    'min' => 2,
                    'max' => 100,
                    'default_value' => 20,
                ],
                [
                    'key' => 'pulse_count',
                    'type' => 'select',
                    'label' => ['en' => 'Pulse Mode', 'ar' => 'وضع النبضة'],
                    'required' => true,
                    'category' => 'timing',
                    'options' => [
                        ['value' => 'single', 'label' => ['en' => 'Single Pulse', 'ar' => 'نبضة واحدة']],
                        ['value' => 'double', 'label' => ['en' => 'Double Pulse', 'ar' => 'نبضة مزدوجة']],
                        ['value' => 'triple', 'label' => ['en' => 'Triple Pulse', 'ar' => 'نبضة ثلاثية']],
                    ],
                    'default_value' => 'double',
                ],
                [
                    'key' => 'pulse_delay',
                    'type' => 'number',
                    'label' => ['en' => 'Pulse Delay', 'ar' => 'تأخير النبضة'],
                    'required' => false,
                    'unit' => 'ms',
                    'category' => 'timing',
                    'min' => 10,
                    'max' => 100,
                    'default_value' => 30,
                ],
                [
                    'key' => 'cooling_temp',
                    'type' => 'number',
                    'label' => ['en' => 'Crystal Cooling', 'ar' => 'تبريد الكريستال'],
                    'required' => false,
                    'unit' => '°C',
                    'category' => 'cooling',
                    'min' => 0,
                    'max' => 15,
                    'default_value' => 5,
                ],
                [
                    'key' => 'shots_fired',
                    'type' => 'number',
                    'label' => ['en' => 'Shots Fired', 'ar' => 'عدد النبضات'],
                    'required' => false,
                    'unit' => 'shots',
                    'category' => 'other',
                    'min' => 0,
                    'max' => 10000,
                    'cumulative' => true,
                ],
            ],
        ];
    }

    protected function getRFEquipmentTemplate(): array
    {
        return [
            'tenant_id' => null,
            'template_name' => 'Radio Frequency Equipment',
            'template_code' => 'EQUIP_RF',
            'description' => 'Standard tracking parameters for Radio Frequency devices',
            'equipment_category' => 'rf',
            'is_system' => true,
            'is_active' => true,
            'parameters' => [
                [
                    'key' => 'rf_mode',
                    'type' => 'select',
                    'label' => ['en' => 'RF Mode', 'ar' => 'وضع الترددات'],
                    'required' => true,
                    'category' => 'energy',
                    'options' => [
                        ['value' => 'monopolar', 'label' => ['en' => 'Monopolar', 'ar' => 'أحادي القطب']],
                        ['value' => 'bipolar', 'label' => ['en' => 'Bipolar', 'ar' => 'ثنائي القطب']],
                        ['value' => 'multipolar', 'label' => ['en' => 'Multipolar', 'ar' => 'متعدد الأقطاب']],
                        ['value' => 'fractional', 'label' => ['en' => 'Fractional RF', 'ar' => 'فراكشنال']],
                    ],
                ],
                [
                    'key' => 'power_level',
                    'type' => 'number',
                    'label' => ['en' => 'Power Level', 'ar' => 'مستوى الطاقة'],
                    'required' => true,
                    'unit' => 'W',
                    'category' => 'energy',
                    'min' => 1,
                    'max' => 100,
                    'default_value' => 30,
                ],
                [
                    'key' => 'frequency',
                    'type' => 'select',
                    'label' => ['en' => 'RF Frequency', 'ar' => 'التردد'],
                    'required' => true,
                    'unit' => 'MHz',
                    'category' => 'energy',
                    'options' => [
                        ['value' => '0.5', 'label' => ['en' => '0.5 MHz', 'ar' => '0.5 ميجاهرتز']],
                        ['value' => '1', 'label' => ['en' => '1 MHz', 'ar' => '1 ميجاهرتز']],
                        ['value' => '2', 'label' => ['en' => '2 MHz', 'ar' => '2 ميجاهرتز']],
                        ['value' => '4', 'label' => ['en' => '4 MHz', 'ar' => '4 ميجاهرتز']],
                        ['value' => '6', 'label' => ['en' => '6 MHz', 'ar' => '6 ميجاهرتز']],
                    ],
                    'default_value' => '2',
                ],
                [
                    'key' => 'treatment_time',
                    'type' => 'number',
                    'label' => ['en' => 'Treatment Time', 'ar' => 'وقت العلاج'],
                    'required' => false,
                    'unit' => 'min',
                    'category' => 'timing',
                    'min' => 5,
                    'max' => 60,
                    'default_value' => 20,
                ],
                [
                    'key' => 'target_temp',
                    'type' => 'number',
                    'label' => ['en' => 'Target Temperature', 'ar' => 'درجة الحرارة المستهدفة'],
                    'required' => false,
                    'unit' => '°C',
                    'category' => 'safety',
                    'min' => 38,
                    'max' => 45,
                    'default_value' => 42,
                ],
                [
                    'key' => 'needle_depth',
                    'type' => 'decimal',
                    'label' => ['en' => 'Needle Depth (if RF Microneedling)', 'ar' => 'عمق الإبرة'],
                    'required' => false,
                    'unit' => 'mm',
                    'category' => 'delivery',
                    'min' => 0.5,
                    'max' => 4.0,
                    'step' => 0.5,
                    'help_text' => ['en' => 'For RF microneedling devices only', 'ar' => 'لأجهزة الديرما RF فقط'],
                ],
                [
                    'key' => 'total_pulses',
                    'type' => 'number',
                    'label' => ['en' => 'Total Pulses', 'ar' => 'إجمالي النبضات'],
                    'required' => false,
                    'unit' => 'pulses',
                    'category' => 'other',
                    'min' => 0,
                    'max' => 5000,
                    'cumulative' => true,
                ],
            ],
        ];
    }

    protected function getHIFUEquipmentTemplate(): array
    {
        return [
            'tenant_id' => null,
            'template_name' => 'HIFU Equipment',
            'template_code' => 'EQUIP_HIFU',
            'description' => 'Standard tracking parameters for High-Intensity Focused Ultrasound devices',
            'equipment_category' => 'hifu',
            'is_system' => true,
            'is_active' => true,
            'parameters' => [
                [
                    'key' => 'cartridge_depth',
                    'type' => 'select',
                    'label' => ['en' => 'Cartridge Depth', 'ar' => 'عمق الخرطوشة'],
                    'required' => true,
                    'unit' => 'mm',
                    'category' => 'delivery',
                    'options' => [
                        ['value' => '1.5', 'label' => ['en' => '1.5mm (Epidermis)', 'ar' => '1.5مم (البشرة)']],
                        ['value' => '3.0', 'label' => ['en' => '3.0mm (Dermis)', 'ar' => '3.0مم (الأدمة)']],
                        ['value' => '4.5', 'label' => ['en' => '4.5mm (SMAS)', 'ar' => '4.5مم (SMAS)']],
                        ['value' => '6.0', 'label' => ['en' => '6.0mm (Body)', 'ar' => '6.0مم (الجسم)']],
                        ['value' => '9.0', 'label' => ['en' => '9.0mm (Body Deep)', 'ar' => '9.0مم (عمق الجسم)']],
                        ['value' => '13.0', 'label' => ['en' => '13.0mm (Fat Layer)', 'ar' => '13.0مم (طبقة الدهون)']],
                    ],
                ],
                [
                    'key' => 'energy_level',
                    'type' => 'decimal',
                    'label' => ['en' => 'Energy Level', 'ar' => 'مستوى الطاقة'],
                    'required' => true,
                    'unit' => 'J',
                    'category' => 'energy',
                    'min' => 0.3,
                    'max' => 3.0,
                    'step' => 0.1,
                    'default_value' => 1.0,
                ],
                [
                    'key' => 'line_length',
                    'type' => 'select',
                    'label' => ['en' => 'Line Length', 'ar' => 'طول الخط'],
                    'required' => true,
                    'unit' => 'mm',
                    'category' => 'delivery',
                    'options' => [
                        ['value' => '5', 'label' => ['en' => '5mm', 'ar' => '5مم']],
                        ['value' => '10', 'label' => ['en' => '10mm', 'ar' => '10مم']],
                        ['value' => '15', 'label' => ['en' => '15mm', 'ar' => '15مم']],
                        ['value' => '25', 'label' => ['en' => '25mm', 'ar' => '25مم']],
                    ],
                    'default_value' => '25',
                ],
                [
                    'key' => 'dot_spacing',
                    'type' => 'decimal',
                    'label' => ['en' => 'Dot Spacing', 'ar' => 'المسافة بين النقاط'],
                    'required' => false,
                    'unit' => 'mm',
                    'category' => 'delivery',
                    'min' => 1.0,
                    'max' => 3.0,
                    'step' => 0.5,
                    'default_value' => 1.5,
                ],
                [
                    'key' => 'total_lines',
                    'type' => 'number',
                    'label' => ['en' => 'Total Lines', 'ar' => 'إجمالي الخطوط'],
                    'required' => true,
                    'category' => 'other',
                    'min' => 0,
                    'max' => 2000,
                    'cumulative' => true,
                ],
                [
                    'key' => 'total_shots',
                    'type' => 'number',
                    'label' => ['en' => 'Total Shots', 'ar' => 'إجمالي النبضات'],
                    'required' => false,
                    'category' => 'other',
                    'min' => 0,
                    'max' => 50000,
                    'cumulative' => true,
                ],
            ],
        ];
    }

    protected function getCryolipolysisEquipmentTemplate(): array
    {
        return [
            'tenant_id' => null,
            'template_name' => 'Cryolipolysis Equipment',
            'template_code' => 'EQUIP_CRYO',
            'description' => 'Standard tracking parameters for fat freezing devices (CoolSculpting, etc.)',
            'equipment_category' => 'cryolipolysis',
            'is_system' => true,
            'is_active' => true,
            'parameters' => [
                [
                    'key' => 'applicator_type',
                    'type' => 'select',
                    'label' => ['en' => 'Applicator Type', 'ar' => 'نوع القبضة'],
                    'required' => true,
                    'category' => 'delivery',
                    'options' => [
                        ['value' => 'small', 'label' => ['en' => 'Small (Chin/Arms)', 'ar' => 'صغير (ذقن/ذراع)']],
                        ['value' => 'medium', 'label' => ['en' => 'Medium (Flanks)', 'ar' => 'متوسط (الجانبين)']],
                        ['value' => 'large', 'label' => ['en' => 'Large (Abdomen)', 'ar' => 'كبير (البطن)']],
                        ['value' => 'curved', 'label' => ['en' => 'Curved (Thighs)', 'ar' => 'منحني (الأفخاذ)']],
                        ['value' => 'flat', 'label' => ['en' => 'Flat (Back)', 'ar' => 'مسطح (الظهر)']],
                    ],
                ],
                [
                    'key' => 'temperature',
                    'type' => 'number',
                    'label' => ['en' => 'Target Temperature', 'ar' => 'درجة الحرارة المستهدفة'],
                    'required' => true,
                    'unit' => '°C',
                    'category' => 'energy',
                    'min' => -15,
                    'max' => 0,
                    'default_value' => -10,
                ],
                [
                    'key' => 'vacuum_level',
                    'type' => 'select',
                    'label' => ['en' => 'Vacuum Level', 'ar' => 'مستوى الشفط'],
                    'required' => true,
                    'category' => 'delivery',
                    'options' => [
                        ['value' => 'low', 'label' => ['en' => 'Low', 'ar' => 'منخفض']],
                        ['value' => 'medium', 'label' => ['en' => 'Medium', 'ar' => 'متوسط']],
                        ['value' => 'high', 'label' => ['en' => 'High', 'ar' => 'عالي']],
                    ],
                    'default_value' => 'medium',
                ],
                [
                    'key' => 'treatment_duration',
                    'type' => 'number',
                    'label' => ['en' => 'Treatment Duration', 'ar' => 'مدة العلاج'],
                    'required' => true,
                    'unit' => 'min',
                    'category' => 'timing',
                    'min' => 25,
                    'max' => 75,
                    'default_value' => 35,
                ],
                [
                    'key' => 'cycles_completed',
                    'type' => 'number',
                    'label' => ['en' => 'Cycles Completed', 'ar' => 'الدورات المكتملة'],
                    'required' => false,
                    'category' => 'other',
                    'min' => 0,
                    'max' => 10,
                    'cumulative' => true,
                ],
            ],
        ];
    }

    protected function getMicroneedlingEquipmentTemplate(): array
    {
        return [
            'tenant_id' => null,
            'template_name' => 'Microneedling Equipment',
            'template_code' => 'EQUIP_MICRONEEDLING',
            'description' => 'Standard tracking parameters for microneedling devices (Dermapen, SkinPen, etc.)',
            'equipment_category' => 'microneedling',
            'is_system' => true,
            'is_active' => true,
            'parameters' => [
                [
                    'key' => 'needle_depth',
                    'type' => 'decimal',
                    'label' => ['en' => 'Needle Depth', 'ar' => 'عمق الإبرة'],
                    'required' => true,
                    'unit' => 'mm',
                    'category' => 'delivery',
                    'min' => 0.25,
                    'max' => 3.0,
                    'step' => 0.25,
                    'default_value' => 1.0,
                ],
                [
                    'key' => 'speed_setting',
                    'type' => 'select',
                    'label' => ['en' => 'Speed Setting', 'ar' => 'إعداد السرعة'],
                    'required' => true,
                    'category' => 'timing',
                    'options' => [
                        ['value' => '1', 'label' => ['en' => 'Level 1 (Slow)', 'ar' => 'المستوى 1 (بطيء)']],
                        ['value' => '2', 'label' => ['en' => 'Level 2', 'ar' => 'المستوى 2']],
                        ['value' => '3', 'label' => ['en' => 'Level 3 (Medium)', 'ar' => 'المستوى 3 (متوسط)']],
                        ['value' => '4', 'label' => ['en' => 'Level 4', 'ar' => 'المستوى 4']],
                        ['value' => '5', 'label' => ['en' => 'Level 5 (Fast)', 'ar' => 'المستوى 5 (سريع)']],
                    ],
                    'default_value' => '3',
                ],
                [
                    'key' => 'needle_cartridge',
                    'type' => 'select',
                    'label' => ['en' => 'Needle Cartridge', 'ar' => 'خرطوشة الإبر'],
                    'required' => true,
                    'category' => 'delivery',
                    'options' => [
                        ['value' => '12pin', 'label' => ['en' => '12 Pin', 'ar' => '12 إبرة']],
                        ['value' => '16pin', 'label' => ['en' => '16 Pin', 'ar' => '16 إبرة']],
                        ['value' => '24pin', 'label' => ['en' => '24 Pin', 'ar' => '24 إبرة']],
                        ['value' => '36pin', 'label' => ['en' => '36 Pin', 'ar' => '36 إبرة']],
                        ['value' => 'nano', 'label' => ['en' => 'Nano (Silicone)', 'ar' => 'نانو (سيليكون)']],
                    ],
                    'default_value' => '16pin',
                ],
                [
                    'key' => 'rf_enabled',
                    'type' => 'boolean',
                    'label' => ['en' => 'RF Enabled', 'ar' => 'RF مفعل'],
                    'required' => false,
                    'category' => 'energy',
                    'default_value' => false,
                    'help_text' => ['en' => 'For RF microneedling devices', 'ar' => 'لأجهزة الديرما RF'],
                ],
                [
                    'key' => 'rf_intensity',
                    'type' => 'number',
                    'label' => ['en' => 'RF Intensity', 'ar' => 'شدة RF'],
                    'required' => false,
                    'unit' => '%',
                    'category' => 'energy',
                    'min' => 10,
                    'max' => 100,
                    'default_value' => 50,
                ],
                [
                    'key' => 'cartridge_lot',
                    'type' => 'text',
                    'label' => ['en' => 'Cartridge Lot Number', 'ar' => 'رقم دفعة الخرطوشة'],
                    'required' => false,
                    'category' => 'safety',
                ],
            ],
        ];
    }

    protected function getHydrafacialEquipmentTemplate(): array
    {
        return [
            'tenant_id' => null,
            'template_name' => 'Hydrafacial Equipment',
            'template_code' => 'EQUIP_HYDRAFACIAL',
            'description' => 'Standard tracking parameters for Hydrafacial and similar hydradermabrasion devices',
            'equipment_category' => 'hydrafacial',
            'is_system' => true,
            'is_active' => true,
            'parameters' => [
                [
                    'key' => 'tip_type',
                    'type' => 'select',
                    'label' => ['en' => 'Tip Type', 'ar' => 'نوع الرأس'],
                    'required' => true,
                    'category' => 'delivery',
                    'options' => [
                        ['value' => 'vortex_cleanse', 'label' => ['en' => 'Vortex Cleanse', 'ar' => 'تنظيف دوامي']],
                        ['value' => 'hydropeel_1', 'label' => ['en' => 'HydroPeel Tip 1', 'ar' => 'رأس التقشير 1']],
                        ['value' => 'hydropeel_2', 'label' => ['en' => 'HydroPeel Tip 2', 'ar' => 'رأس التقشير 2']],
                        ['value' => 'hydropeel_3', 'label' => ['en' => 'HydroPeel Tip 3', 'ar' => 'رأس التقشير 3']],
                        ['value' => 'fusion', 'label' => ['en' => 'Vortex Fusion', 'ar' => 'دمج دوامي']],
                    ],
                ],
                [
                    'key' => 'vacuum_level',
                    'type' => 'number',
                    'label' => ['en' => 'Vacuum Level', 'ar' => 'مستوى الشفط'],
                    'required' => true,
                    'unit' => '%',
                    'category' => 'delivery',
                    'min' => 10,
                    'max' => 100,
                    'default_value' => 50,
                ],
                [
                    'key' => 'serum_used',
                    'type' => 'select',
                    'label' => ['en' => 'Serum/Solution', 'ar' => 'السيروم/المحلول'],
                    'required' => true,
                    'category' => 'other',
                    'options' => [
                        ['value' => 'activ4', 'label' => ['en' => 'Activ-4 (Cleanse)', 'ar' => 'أكتيف-4 (تنظيف)']],
                        ['value' => 'glysal', 'label' => ['en' => 'GlySal (Exfoliate)', 'ar' => 'جليسال (تقشير)']],
                        ['value' => 'beta_hd', 'label' => ['en' => 'Beta-HD (Extract)', 'ar' => 'بيتا-HD (استخراج)']],
                        ['value' => 'antiox', 'label' => ['en' => 'Antiox+ (Hydrate)', 'ar' => 'أنتيوكس+ (ترطيب)']],
                        ['value' => 'dermabuilder', 'label' => ['en' => 'DermaBuilder (Peptides)', 'ar' => 'ديرمابيلدر (ببتيدات)']],
                        ['value' => 'britenol', 'label' => ['en' => 'Britenol (Brighten)', 'ar' => 'برايتنول (تفتيح)']],
                    ],
                ],
                [
                    'key' => 'led_used',
                    'type' => 'boolean',
                    'label' => ['en' => 'LED Light Therapy Used', 'ar' => 'تم استخدام العلاج بالضوء'],
                    'required' => false,
                    'category' => 'other',
                    'default_value' => false,
                ],
                [
                    'key' => 'led_color',
                    'type' => 'select',
                    'label' => ['en' => 'LED Color', 'ar' => 'لون LED'],
                    'required' => false,
                    'category' => 'energy',
                    'options' => [
                        ['value' => 'red', 'label' => ['en' => 'Red (Anti-aging)', 'ar' => 'أحمر (مقاومة الشيخوخة)']],
                        ['value' => 'blue', 'label' => ['en' => 'Blue (Acne)', 'ar' => 'أزرق (حب الشباب)']],
                        ['value' => 'infrared', 'label' => ['en' => 'Infrared (Deep Healing)', 'ar' => 'تحت الحمراء (شفاء عميق)']],
                    ],
                ],
            ],
        ];
    }

    protected function getLEDEquipmentTemplate(): array
    {
        return [
            'tenant_id' => null,
            'template_name' => 'LED Therapy Equipment',
            'template_code' => 'EQUIP_LED',
            'description' => 'Standard tracking parameters for LED light therapy devices',
            'equipment_category' => 'led',
            'is_system' => true,
            'is_active' => true,
            'parameters' => [
                [
                    'key' => 'light_color',
                    'type' => 'select',
                    'label' => ['en' => 'Light Color/Wavelength', 'ar' => 'لون/طول موجة الضوء'],
                    'required' => true,
                    'category' => 'energy',
                    'options' => [
                        ['value' => 'red_633', 'label' => ['en' => 'Red (633nm) - Collagen', 'ar' => 'أحمر (633nm) - كولاجين']],
                        ['value' => 'red_830', 'label' => ['en' => 'Near Infrared (830nm) - Deep', 'ar' => 'قرب الحمراء (830nm) - عميق']],
                        ['value' => 'blue_415', 'label' => ['en' => 'Blue (415nm) - Acne', 'ar' => 'أزرق (415nm) - حب الشباب']],
                        ['value' => 'amber_590', 'label' => ['en' => 'Amber (590nm) - Redness', 'ar' => 'كهرماني (590nm) - احمرار']],
                        ['value' => 'green_525', 'label' => ['en' => 'Green (525nm) - Pigment', 'ar' => 'أخضر (525nm) - تصبغ']],
                        ['value' => 'combo', 'label' => ['en' => 'Combination', 'ar' => 'مجموعة']],
                    ],
                ],
                [
                    'key' => 'intensity',
                    'type' => 'number',
                    'label' => ['en' => 'Intensity Level', 'ar' => 'مستوى الشدة'],
                    'required' => true,
                    'unit' => '%',
                    'category' => 'energy',
                    'min' => 10,
                    'max' => 100,
                    'default_value' => 80,
                ],
                [
                    'key' => 'treatment_time',
                    'type' => 'number',
                    'label' => ['en' => 'Treatment Time', 'ar' => 'وقت العلاج'],
                    'required' => true,
                    'unit' => 'min',
                    'category' => 'timing',
                    'min' => 5,
                    'max' => 30,
                    'default_value' => 20,
                ],
                [
                    'key' => 'pulsed_mode',
                    'type' => 'boolean',
                    'label' => ['en' => 'Pulsed Mode', 'ar' => 'الوضع النبضي'],
                    'required' => false,
                    'category' => 'timing',
                    'default_value' => false,
                ],
                [
                    'key' => 'pulse_frequency',
                    'type' => 'number',
                    'label' => ['en' => 'Pulse Frequency', 'ar' => 'تردد النبضة'],
                    'required' => false,
                    'unit' => 'Hz',
                    'category' => 'timing',
                    'min' => 1,
                    'max' => 100,
                    'help_text' => ['en' => 'Only when pulsed mode is enabled', 'ar' => 'فقط عند تفعيل الوضع النبضي'],
                ],
                [
                    'key' => 'distance_from_skin',
                    'type' => 'select',
                    'label' => ['en' => 'Distance from Skin', 'ar' => 'المسافة من الجلد'],
                    'required' => false,
                    'category' => 'delivery',
                    'options' => [
                        ['value' => 'contact', 'label' => ['en' => 'Contact', 'ar' => 'ملامس']],
                        ['value' => '5cm', 'label' => ['en' => '5cm', 'ar' => '5 سم']],
                        ['value' => '10cm', 'label' => ['en' => '10cm', 'ar' => '10 سم']],
                        ['value' => '15cm', 'label' => ['en' => '15cm', 'ar' => '15 سم']],
                    ],
                    'default_value' => '5cm',
                ],
            ],
        ];
    }
}
