@php $brand = \App\Models\PlatformSetting::get('platform_name', 'XForce'); @endphp

<p>
    This Privacy Policy explains how <strong>{{ $brand }}</strong> handles personal information when you use
    our HR operating system, web admin panels, and mobile applications (together, the &ldquo;<strong>Service</strong>&rdquo;).
    We comply with the Egyptian Personal Data Protection Law No.&nbsp;151 of 2020 and draw on internationally
    recognised principles, including those reflected in the EU GDPR.
</p>

<blockquote>
    <strong>Two roles you should understand.</strong> {{ $brand }} acts as a <strong>data controller</strong>
    for the small set of information we receive directly to provide and run the Service (for example, your
    account credentials and billing details). For the much larger set of HR data that an employer enters
    about its workforce &mdash; salaries, attendance, leave, contracts, identification documents &mdash;
    {{ $brand }} acts as a <strong>data processor</strong>. The employer is the controller of that data and
    decides what is uploaded, who can see it, and how long it is retained. {{ $brand }} only stores and
    processes it as instructed by the employer.
</blockquote>

<h2 id="who-we-are" class="toc-anchor">1. Who we are</h2>
<p>
    {{ $brand }} is an HR software-as-a-service platform that helps companies manage employee records,
    attendance, leave, payroll, and loans. For any privacy-related question, contact us at
    <a href="mailto:privacy@xforcehr.com">privacy@xforcehr.com</a>.
</p>

<h2 id="information-we-receive" class="toc-anchor">2. Information we receive</h2>

<h3>From you (when you create or use a {{ $brand }} account)</h3>
<ul>
    <li>Account credentials: name, email address, phone number, hashed password, optional two-factor authentication secret.</li>
    <li>Profile basics: avatar, role, branch, language preference.</li>
</ul>

<h3>From the subscribing employer (for billing)</h3>
<ul>
    <li>Organisation name, billing contact, tax ID.</li>
    <li>Subscription plan, billing cycle, payment method tokens. We do not store full card numbers; payment data is tokenised by our payment processor.</li>
</ul>

<h3>From your mobile device (only when you use the {{ $brand }} app)</h3>
<ul>
    <li>Device push token (Firebase Cloud Messaging), device model, OS version, app version, IP address, timezone.</li>
    <li>Geolocation captured at check-in / check-out only if your employer has enabled geofencing.</li>
    <li>Biometric authentication result (pass/fail only) &mdash; if you enable fingerprint or Face ID app unlock, your biometric template is stored and matched entirely within your device&rsquo;s secure hardware enclave. {{ $brand }} only receives a pass/fail signal from the operating system and never stores or transmits biometric data.</li>
</ul>

<h3>Automatically (security and operations)</h3>
<ul>
    <li>Server logs &mdash; IP address, user-agent, request paths, timestamps &mdash; used for security, abuse prevention, and debugging.</li>
    <li>An audit log of significant actions inside your workspace (creations, updates, deletions).</li>
</ul>

<h2 id="employer-uploaded-data" class="toc-anchor">3. HR data uploaded by employers</h2>
<p>
    The Service is a platform that lets employers manage their workforce. Your employer enters or records
    information in {{ $brand }} &mdash; for example, your job title, salary, attendance check-ins, leave
    balances, contracts, and identification documents. {{ $brand }} does not actively collect this data;
    it is uploaded or generated by your employer in the course of using the Service, and {{ $brand }}
    stores and processes it strictly on the employer&rsquo;s behalf as a data processor. Some
    employer-uploaded data (such as identification documents and financial records) may constitute
    sensitive personal data under Egyptian Law&nbsp;151/2020, and {{ $brand }} applies technical and
    contractual measures appropriate to that classification.
</p>
<p>
    If you are an employee, your employer is the controller of this data. Questions about your specific
    HR records (what is stored about you, who can see it, how long it is retained) should be directed to
    your employer&rsquo;s HR team. We will support the employer in responding.
</p>

<h2 id="why-we-process" class="toc-anchor">4. Why we process this information</h2>
<ul>
    <li><strong>Performance of contract:</strong> to deliver the features the customer subscribed to.</li>
    <li><strong>Legal obligation:</strong> issuing tax invoices and supporting employer compliance with Egyptian Labor Law, Social Insurance Law, and Tax Law.</li>
    <li><strong>Legitimate interest:</strong> security monitoring, fraud detection, and product improvement using aggregated, non-identifying data.</li>
    <li><strong>Consent:</strong> for optional product newsletters and marketing emails &mdash; you can withdraw at any time.</li>
</ul>

<h2 id="retention" class="toc-anchor">5. How long we keep information</h2>
<ul>
    <li><strong>Employer-uploaded HR data:</strong> retained while the employer&rsquo;s subscription is active and for the period required by the employer&rsquo;s legal obligations under Egyptian Labor Law, Social Insurance Law, and Tax Law. The employer controls deletion through {{ $brand }}.</li>
    <li><strong>User account data:</strong> personal data (name, email, phone, profile) is purged within 30 days of account deletion. Account identifiers are retained for up to 90 days for audit and dispute resolution, then deleted.</li>
    <li><strong>Mobile push tokens, notification preferences:</strong> removed immediately on account deletion or device unregistration.</li>
    <li><strong>Server logs:</strong> 90 days, except where a longer period is necessary for an open security incident.</li>
</ul>

<h2 id="sharing" class="toc-anchor">6. Who we share information with</h2>
<p>
    {{ $brand }} does not sell personal data. We share data only with vetted third-party processors who
    help us deliver the Service, and only to the extent necessary. Categories of subprocessor:
</p>
<ul>
    <li><strong>Cloud hosting</strong> &mdash; hosts the application and the customer database.</li>
    <li><strong>Push notifications</strong> &mdash; Google Firebase Cloud Messaging, used to deliver mobile push notifications.</li>
    <li><strong>Transactional email</strong> &mdash; for account-related emails (password reset, alerts).</li>
    <li><strong>SMS / WhatsApp</strong> &mdash; for OTP and operational notifications when enabled.</li>
    <li><strong>Payment processing</strong> &mdash; for {{ $brand }} subscription billing only; no employee payroll data is sent to the payment processor.</li>
</ul>
<p>
    Some of these subprocessors (notably Firebase/Google) operate outside Egypt. Data transferred
    internationally is encrypted in transit and protected by standard contractual clauses or equivalent
    safeguards recognised under Egyptian Law&nbsp;151/2020 Art.&nbsp;12.
</p>

<h2 id="security" class="toc-anchor">7. How we keep information safe</h2>
<ul>
    <li>Encryption in transit (TLS&nbsp;1.2+) and at rest (database and backup encryption).</li>
    <li>Per-employer database schema isolation: each company&rsquo;s data lives in a separate PostgreSQL schema.</li>
    <li>Role-based access control with optional two-factor authentication.</li>
    <li>Rate limiting and brute-force protection on authentication endpoints.</li>
    <li>Audit logging of sensitive actions; security review of new releases.</li>
</ul>
<p>
    In the event of a personal data breach, {{ $brand }} will notify the Personal Data Protection Centre
    (PDPC) and affected parties without undue delay in accordance with Egyptian Law&nbsp;151/2020.
    To report a suspected security issue, contact <a href="mailto:security@xforcehr.com">security@xforcehr.com</a>.
</p>

<h2 id="your-rights" class="toc-anchor">8. Your rights</h2>
<p>
    Under Egyptian Law&nbsp;151/2020 and equivalent regimes you have rights of access, correction, deletion,
    restriction, portability, objection, and withdrawal of consent.
</p>
<p>
    If you are an employee, requests about your HR records should generally go to your employer (the
    controller). Requests that concern {{ $brand }} directly &mdash; for example, deleting your mobile-app
    account &mdash; can be sent to <a href="mailto:privacy@xforcehr.com">privacy@xforcehr.com</a>. If you are
    unable to reach your employer&rsquo;s HR team, contact us directly and we will assist. We respond
    within 30 days and may ask you to verify your identity first.
</p>

<h2 id="account-deletion" class="toc-anchor">9. Account deletion</h2>
<p>
    Mobile-app users can delete their {{ $brand }} account from
    <strong>Settings &rarr; Account &rarr; Delete account</strong>. Confirmation requires re-entering your
    password. On confirmation:
</p>
<ul>
    <li>All active sessions and access tokens are revoked across every device.</li>
    <li>The account is marked as deleted and can no longer authenticate.</li>
    <li>Mobile push tokens and notification preferences are removed immediately.</li>
    <li>Personal data (name, email address, phone number, profile) is permanently purged within 30 days. Account identifiers may be retained for up to 90 days solely for audit and dispute resolution, after which they are deleted.</li>
    <li>HR records that relate to your employment (attendance, leave, payroll) are retained by your employer, which is the data controller and is bound by Egyptian labor and tax retention laws.</li>
</ul>
<p>
    No mobile-app access? Email <a href="mailto:privacy@xforcehr.com">privacy@xforcehr.com</a> and we will
    process the request manually.
</p>

<h2 id="children" class="toc-anchor">10. Children&rsquo;s data</h2>
<p>
    {{ $brand }} is not directed at children under 18. We do not knowingly create accounts for minors.
    If you believe a minor has registered, contact us and we will remove the account.
</p>

<h2 id="cookies" class="toc-anchor">11. Cookies</h2>
<p>
    We use only essential cookies (sign-in sessions, CSRF protection, language preference). We do not
    currently use third-party analytics on the marketing site or admin panels. Blocking cookies in your
    browser may break sign-in.
</p>

<h2 id="changes" class="toc-anchor">12. Changes to this policy</h2>
<p>
    We may update this Privacy Policy from time to time. Material changes are notified to active customer
    administrators by email at least 14 days in advance, and the date at the top of this page reflects the
    latest version.
</p>

<h2 id="contact" class="toc-anchor">13. Contact</h2>
<ul>
    <li>Privacy questions: <a href="mailto:privacy@xforcehr.com">privacy@xforcehr.com</a></li>
    <li>Security disclosures: <a href="mailto:security@xforcehr.com">security@xforcehr.com</a></li>
    <li>Data-subject requests: your employer&rsquo;s HR team, or <a href="mailto:privacy@xforcehr.com">privacy@xforcehr.com</a> if you cannot reach them</li>
</ul>
