<?php

namespace Modules\Prescriptions\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Prescriptions\Models\MedicineCatalog;

class DefaultMedicinesSeeder extends Seeder
{
    public function run(): void
    {
        $medicines = [
            // Antibiotics
            [
                'brand_name' => 'Amoxicillin',
                'generic_name' => 'Amoxicillin',
                'category' => 'antibiotic',
                'drug_class' => 'Penicillin',
                'form' => 'capsule',
                'strength' => '500',
                'strength_unit' => 'mg',
                'default_dosage' => '500',
                'default_dosage_unit' => 'mg',
                'default_frequency' => 'three_times_daily',
                'default_duration' => 7,
                'default_duration_unit' => 'days',
                'default_route' => 'oral',
                'default_instructions' => 'after_meal',
                'indications' => 'Bacterial infections, respiratory tract infections, urinary tract infections',
                'contraindications' => 'Penicillin allergy',
            ],
            [
                'brand_name' => 'Azithromycin',
                'generic_name' => 'Azithromycin',
                'category' => 'antibiotic',
                'drug_class' => 'Macrolide',
                'form' => 'tablet',
                'strength' => '500',
                'strength_unit' => 'mg',
                'default_dosage' => '500',
                'default_dosage_unit' => 'mg',
                'default_frequency' => 'once_daily',
                'default_duration' => 3,
                'default_duration_unit' => 'days',
                'default_route' => 'oral',
                'default_instructions' => 'before_meal',
                'indications' => 'Respiratory infections, skin infections, STIs',
                'contraindications' => 'Macrolide allergy, liver disease',
            ],
            [
                'brand_name' => 'Ciprofloxacin',
                'generic_name' => 'Ciprofloxacin',
                'category' => 'antibiotic',
                'drug_class' => 'Fluoroquinolone',
                'form' => 'tablet',
                'strength' => '500',
                'strength_unit' => 'mg',
                'default_dosage' => '500',
                'default_dosage_unit' => 'mg',
                'default_frequency' => 'twice_daily',
                'default_duration' => 7,
                'default_duration_unit' => 'days',
                'default_route' => 'oral',
                'default_instructions' => 'with_water',
                'indications' => 'Urinary tract infections, respiratory infections',
                'contraindications' => 'Pregnancy, tendon disorders',
            ],
            [
                'brand_name' => 'Metronidazole',
                'generic_name' => 'Metronidazole',
                'category' => 'antibiotic',
                'drug_class' => 'Nitroimidazole',
                'form' => 'tablet',
                'strength' => '500',
                'strength_unit' => 'mg',
                'default_dosage' => '500',
                'default_dosage_unit' => 'mg',
                'default_frequency' => 'three_times_daily',
                'default_duration' => 7,
                'default_duration_unit' => 'days',
                'default_route' => 'oral',
                'default_instructions' => 'after_meal',
                'indications' => 'Anaerobic infections, dental infections, GI infections',
                'contraindications' => 'Alcohol consumption during treatment',
            ],

            // Analgesics / Pain Relief
            [
                'brand_name' => 'Paracetamol',
                'generic_name' => 'Acetaminophen',
                'category' => 'analgesic',
                'drug_class' => 'Analgesic/Antipyretic',
                'form' => 'tablet',
                'strength' => '500',
                'strength_unit' => 'mg',
                'default_dosage' => '500',
                'default_dosage_unit' => 'mg',
                'default_frequency' => 'three_times_daily',
                'default_duration' => 5,
                'default_duration_unit' => 'days',
                'default_route' => 'oral',
                'default_instructions' => 'as_directed',
                'indications' => 'Pain relief, fever reduction',
                'contraindications' => 'Severe liver disease',
                'warnings' => 'Do not exceed 4g daily',
            ],
            [
                'brand_name' => 'Ibuprofen',
                'generic_name' => 'Ibuprofen',
                'category' => 'anti_inflammatory',
                'drug_class' => 'NSAID',
                'form' => 'tablet',
                'strength' => '400',
                'strength_unit' => 'mg',
                'default_dosage' => '400',
                'default_dosage_unit' => 'mg',
                'default_frequency' => 'three_times_daily',
                'default_duration' => 5,
                'default_duration_unit' => 'days',
                'default_route' => 'oral',
                'default_instructions' => 'after_meal',
                'indications' => 'Pain, inflammation, fever',
                'contraindications' => 'Peptic ulcer, renal impairment, aspirin allergy',
            ],
            [
                'brand_name' => 'Diclofenac',
                'generic_name' => 'Diclofenac Sodium',
                'category' => 'anti_inflammatory',
                'drug_class' => 'NSAID',
                'form' => 'tablet',
                'strength' => '50',
                'strength_unit' => 'mg',
                'default_dosage' => '50',
                'default_dosage_unit' => 'mg',
                'default_frequency' => 'twice_daily',
                'default_duration' => 5,
                'default_duration_unit' => 'days',
                'default_route' => 'oral',
                'default_instructions' => 'after_meal',
                'indications' => 'Pain, inflammation, arthritis',
                'contraindications' => 'GI bleeding, heart failure',
            ],

            // Antihistamines
            [
                'brand_name' => 'Cetirizine',
                'generic_name' => 'Cetirizine HCL',
                'category' => 'antihistamine',
                'drug_class' => 'H1 Antihistamine',
                'form' => 'tablet',
                'strength' => '10',
                'strength_unit' => 'mg',
                'default_dosage' => '10',
                'default_dosage_unit' => 'mg',
                'default_frequency' => 'once_daily',
                'default_duration' => 7,
                'default_duration_unit' => 'days',
                'default_route' => 'oral',
                'default_instructions' => 'at_bedtime',
                'indications' => 'Allergies, hay fever, urticaria',
                'side_effects' => 'Drowsiness',
            ],
            [
                'brand_name' => 'Loratadine',
                'generic_name' => 'Loratadine',
                'category' => 'antihistamine',
                'drug_class' => 'H1 Antihistamine',
                'form' => 'tablet',
                'strength' => '10',
                'strength_unit' => 'mg',
                'default_dosage' => '10',
                'default_dosage_unit' => 'mg',
                'default_frequency' => 'once_daily',
                'default_duration' => 7,
                'default_duration_unit' => 'days',
                'default_route' => 'oral',
                'default_instructions' => 'in_morning',
                'indications' => 'Allergies, hay fever (non-drowsy)',
            ],

            // GI Medications
            [
                'brand_name' => 'Omeprazole',
                'generic_name' => 'Omeprazole',
                'category' => 'antacid',
                'drug_class' => 'Proton Pump Inhibitor',
                'form' => 'capsule',
                'strength' => '20',
                'strength_unit' => 'mg',
                'default_dosage' => '20',
                'default_dosage_unit' => 'mg',
                'default_frequency' => 'once_daily',
                'default_duration' => 14,
                'default_duration_unit' => 'days',
                'default_route' => 'oral',
                'default_instructions' => 'before_meal',
                'indications' => 'GERD, peptic ulcer, gastritis',
            ],
            [
                'brand_name' => 'Ranitidine',
                'generic_name' => 'Ranitidine',
                'category' => 'antacid',
                'drug_class' => 'H2 Blocker',
                'form' => 'tablet',
                'strength' => '150',
                'strength_unit' => 'mg',
                'default_dosage' => '150',
                'default_dosage_unit' => 'mg',
                'default_frequency' => 'twice_daily',
                'default_duration' => 14,
                'default_duration_unit' => 'days',
                'default_route' => 'oral',
                'default_instructions' => 'before_meal',
                'indications' => 'Acid reflux, peptic ulcer',
            ],
            [
                'brand_name' => 'Metoclopramide',
                'generic_name' => 'Metoclopramide',
                'category' => 'antiemetic',
                'drug_class' => 'Prokinetic',
                'form' => 'tablet',
                'strength' => '10',
                'strength_unit' => 'mg',
                'default_dosage' => '10',
                'default_dosage_unit' => 'mg',
                'default_frequency' => 'three_times_daily',
                'default_duration' => 5,
                'default_duration_unit' => 'days',
                'default_route' => 'oral',
                'default_instructions' => 'before_meal',
                'indications' => 'Nausea, vomiting, gastroparesis',
            ],

            // Respiratory
            [
                'brand_name' => 'Salbutamol',
                'generic_name' => 'Albuterol',
                'category' => 'respiratory',
                'drug_class' => 'Beta-2 Agonist',
                'form' => 'inhaler',
                'strength' => '100',
                'strength_unit' => 'mcg',
                'default_dosage' => '2',
                'default_dosage_unit' => 'puff',
                'default_frequency' => 'as_needed',
                'default_route' => 'inhalation',
                'indications' => 'Asthma, bronchospasm, COPD',
            ],
            [
                'brand_name' => 'Montelukast',
                'generic_name' => 'Montelukast Sodium',
                'category' => 'respiratory',
                'drug_class' => 'Leukotriene Antagonist',
                'form' => 'tablet',
                'strength' => '10',
                'strength_unit' => 'mg',
                'default_dosage' => '10',
                'default_dosage_unit' => 'mg',
                'default_frequency' => 'once_daily',
                'default_duration' => 30,
                'default_duration_unit' => 'days',
                'default_route' => 'oral',
                'default_instructions' => 'at_bedtime',
                'indications' => 'Asthma prophylaxis, allergic rhinitis',
            ],

            // Cardiovascular
            [
                'brand_name' => 'Amlodipine',
                'generic_name' => 'Amlodipine Besylate',
                'category' => 'antihypertensive',
                'drug_class' => 'Calcium Channel Blocker',
                'form' => 'tablet',
                'strength' => '5',
                'strength_unit' => 'mg',
                'default_dosage' => '5',
                'default_dosage_unit' => 'mg',
                'default_frequency' => 'once_daily',
                'default_duration' => 30,
                'default_duration_unit' => 'days',
                'default_route' => 'oral',
                'indications' => 'Hypertension, angina',
            ],
            [
                'brand_name' => 'Atenolol',
                'generic_name' => 'Atenolol',
                'category' => 'antihypertensive',
                'drug_class' => 'Beta Blocker',
                'form' => 'tablet',
                'strength' => '50',
                'strength_unit' => 'mg',
                'default_dosage' => '50',
                'default_dosage_unit' => 'mg',
                'default_frequency' => 'once_daily',
                'default_duration' => 30,
                'default_duration_unit' => 'days',
                'default_route' => 'oral',
                'indications' => 'Hypertension, angina, arrhythmias',
                'contraindications' => 'Asthma, bradycardia',
            ],

            // Vitamins & Supplements
            [
                'brand_name' => 'Vitamin D3',
                'generic_name' => 'Cholecalciferol',
                'category' => 'vitamin',
                'drug_class' => 'Vitamin',
                'form' => 'tablet',
                'strength' => '1000',
                'strength_unit' => 'IU',
                'default_dosage' => '1000',
                'default_dosage_unit' => 'IU',
                'default_frequency' => 'once_daily',
                'default_duration' => 30,
                'default_duration_unit' => 'days',
                'default_route' => 'oral',
                'default_instructions' => 'with_food',
                'indications' => 'Vitamin D deficiency, bone health',
                'requires_prescription' => false,
            ],
            [
                'brand_name' => 'Vitamin B Complex',
                'generic_name' => 'B Vitamins',
                'category' => 'vitamin',
                'drug_class' => 'Vitamin',
                'form' => 'tablet',
                'default_frequency' => 'once_daily',
                'default_duration' => 30,
                'default_duration_unit' => 'days',
                'default_route' => 'oral',
                'default_instructions' => 'after_meal',
                'indications' => 'B vitamin deficiency, general health',
                'requires_prescription' => false,
            ],
            [
                'brand_name' => 'Iron Supplement',
                'generic_name' => 'Ferrous Sulfate',
                'category' => 'vitamin',
                'drug_class' => 'Mineral',
                'form' => 'tablet',
                'strength' => '325',
                'strength_unit' => 'mg',
                'default_dosage' => '325',
                'default_dosage_unit' => 'mg',
                'default_frequency' => 'once_daily',
                'default_duration' => 30,
                'default_duration_unit' => 'days',
                'default_route' => 'oral',
                'default_instructions' => 'empty_stomach',
                'indications' => 'Iron deficiency anemia',
            ],

            // Muscle Relaxants
            [
                'brand_name' => 'Cyclobenzaprine',
                'generic_name' => 'Cyclobenzaprine HCL',
                'category' => 'muscle_relaxant',
                'drug_class' => 'Muscle Relaxant',
                'form' => 'tablet',
                'strength' => '10',
                'strength_unit' => 'mg',
                'default_dosage' => '10',
                'default_dosage_unit' => 'mg',
                'default_frequency' => 'three_times_daily',
                'default_duration' => 7,
                'default_duration_unit' => 'days',
                'default_route' => 'oral',
                'indications' => 'Muscle spasms, back pain',
                'side_effects' => 'Drowsiness, dry mouth',
            ],

            // Antifungals
            [
                'brand_name' => 'Fluconazole',
                'generic_name' => 'Fluconazole',
                'category' => 'antifungal',
                'drug_class' => 'Azole Antifungal',
                'form' => 'capsule',
                'strength' => '150',
                'strength_unit' => 'mg',
                'default_dosage' => '150',
                'default_dosage_unit' => 'mg',
                'default_frequency' => 'once_daily',
                'default_duration' => 1,
                'default_duration_unit' => 'days',
                'default_route' => 'oral',
                'indications' => 'Fungal infections, candidiasis',
            ],

            // Dermatological
            [
                'brand_name' => 'Hydrocortisone Cream',
                'generic_name' => 'Hydrocortisone',
                'category' => 'dermatological',
                'drug_class' => 'Corticosteroid',
                'form' => 'cream',
                'strength' => '1',
                'strength_unit' => '%',
                'default_frequency' => 'twice_daily',
                'default_duration' => 7,
                'default_duration_unit' => 'days',
                'default_route' => 'topical',
                'default_instructions' => 'apply_affected',
                'indications' => 'Eczema, dermatitis, itching',
            ],
            [
                'brand_name' => 'Clotrimazole Cream',
                'generic_name' => 'Clotrimazole',
                'category' => 'antifungal',
                'drug_class' => 'Azole Antifungal',
                'form' => 'cream',
                'strength' => '1',
                'strength_unit' => '%',
                'default_frequency' => 'twice_daily',
                'default_duration' => 14,
                'default_duration_unit' => 'days',
                'default_route' => 'topical',
                'default_instructions' => 'apply_affected',
                'indications' => 'Fungal skin infections, athlete\'s foot',
            ],

            // Eye Drops
            [
                'brand_name' => 'Artificial Tears',
                'generic_name' => 'Carboxymethylcellulose',
                'category' => 'ophthalmic',
                'drug_class' => 'Lubricant',
                'form' => 'drops',
                'default_dosage' => '1',
                'default_dosage_unit' => 'drop',
                'default_frequency' => 'as_needed',
                'default_route' => 'ophthalmic',
                'indications' => 'Dry eyes',
                'requires_prescription' => false,
            ],
        ];

        foreach ($medicines as $medicine) {
            MedicineCatalog::updateOrCreate(
                [
                    'brand_name' => $medicine['brand_name'],
                    'tenant_id' => null,
                ],
                array_merge($medicine, [
                    'is_system' => true,
                    'is_active' => true,
                    'requires_prescription' => $medicine['requires_prescription'] ?? true,
                ])
            );
        }
    }
}
